version: "3"
services:
  php:
    build: .
    container_name: "apache_php"
    image: php:8.1.16-apache
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80
  
  db:
    image: mariadb:10.5
    container_name: "mariadb-server"
    restart: always
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
  
  adminer:
    image: adminer:4.8.1
    container_name: "adminer"
    restart: always
    ports:
      - 8080:8080