-- MySQL Script generated by MySQL Workbench
-- Thu Sep  5 15:14:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetoVeiculos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetoVeiculos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoVeiculos` ;
USE `projetoVeiculos` ;

-- -----------------------------------------------------
-- Table `projetoVeiculos`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoVeiculos`.`veiculo` (
  `idveiculo` INT NOT NULL AUTO_INCREMENT,
  `km_atual` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`idveiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoVeiculos`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoVeiculos`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoVeiculos`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoVeiculos`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idfuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoVeiculos`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoVeiculos`.`emprestimo` (
  `idemprestimo` INT NOT NULL AUTO_INCREMENT,
  `idfuncionario` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `data` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idemprestimo`),
  INDEX `fk_emprestimo_funcionario_idx` (`idfuncionario` ASC) VISIBLE,
  INDEX `fk_emprestimo_cliente1_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_funcionario`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `projetoVeiculos`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `projetoVeiculos`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoVeiculos`.`emprestimo_has_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoVeiculos`.`emprestimo_has_veiculo` (
  `idemprestimo` INT NOT NULL,
  `idveiculo` INT NOT NULL,
  `km_inicial` VARCHAR(45) NULL,
  `km_final` VARCHAR(45) NULL,
  PRIMARY KEY (`idemprestimo`, `idveiculo`),
  INDEX `fk_emprestimo_has_veiculo_veiculo1_idx` (`idveiculo` ASC) VISIBLE,
  INDEX `fk_emprestimo_has_veiculo_emprestimo1_idx` (`idemprestimo` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_has_veiculo_emprestimo1`
    FOREIGN KEY (`idemprestimo`)
    REFERENCES `projetoVeiculos`.`emprestimo` (`idemprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_has_veiculo_veiculo1`
    FOREIGN KEY (`idveiculo`)
    REFERENCES `projetoVeiculos`.`veiculo` (`idveiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoVeiculos`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoVeiculos`.`pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `idemprestimo` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `preco_por_km` DECIMAL(10,2) NOT NULL,
  `pagamento` TIMESTAMP NOT NULL,
  `metodo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpagamento`),
  INDEX `fk_pagamento_emprestimo1_idx` (`idemprestimo` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_emprestimo1`
    FOREIGN KEY (`idemprestimo`)
    REFERENCES `projetoVeiculos`.`emprestimo` (`idemprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO cliente (nome) VALUES ('ClienteA');
INSERT INTO cliente (nome) VALUES ('ClienteB');
INSERT INTO cliente (nome) VALUES ('ClienteC');
INSERT INTO cliente (nome) VALUES ('ClienteD');
INSERT INTO cliente (nome) VALUES ('ClienteE');
INSERT INTO cliente (nome) VALUES ('ClienteF');

INSERT INTO funcionario (nome) VALUES ('FuncionarioA');
INSERT INTO funcionario (nome) VALUES ('FuncionarioB');
INSERT INTO funcionario (nome) VALUES ('FuncionarioC');
INSERT INTO funcionario (nome) VALUES ('FuncionarioD');
INSERT INTO funcionario (nome) VALUES ('FuncionarioE');
INSERT INTO funcionario (nome) VALUES ('FuncionarioF');

INSERT INTO veiculo (km_atual, marca, modelo) VALUES('1500','Ford','Ka');
INSERT INTO veiculo (km_atual, marca, modelo) VALUES('32000','Volkswagen','Fusca');
INSERT INTO veiculo (km_atual, marca, modelo) VALUES('2500','Ford','Focus');
INSERT INTO veiculo (km_atual, marca, modelo) VALUES('34500','Fiat','Uno');
INSERT INTO veiculo (km_atual, marca, modelo) VALUES('100','Volkswagen','Polo');
INSERT INTO veiculo (km_atual, marca, modelo) VALUES('1320','Ford','Fusion');